export const mockOrderData = [
    {
        "totalPriceProduct": 539000,
        "shipFees": 30000,
        "finalPrice": 509000,
        "address": "Số 123, Phố Trần Hưng Đạo, Phường Trần Hưng Đạo, Quận Hoàn Kiếm, Hà Nội.",
        "phoneNumber": "string",
        "status": "CREATED",
        "user": {
            "firstName": "string",
            "lastName": "string",
            "address": "string",
            "id": "71aca016-8135-413d-949b-14b56de5d8af",
            "userName": "string",
            "normalizedUserName": null,
            "email": "string",
            "normalizedEmail": null,
            "emailConfirmed": false,
            "passwordHash": null,
            "securityStamp": "7b3086a6-5fbd-437b-aea5-2d499d853df9",
            "concurrencyStamp": "63045963-59bf-44c9-befa-dc86435fcf06",
            "phoneNumber": "string",
            "phoneNumberConfirmed": false,
            "twoFactorEnabled": false,
            "lockoutEnd": null,
            "lockoutEnabled": false,
            "accessFailedCount": 0
        },
        "id": "c709ae6f-1e55-452a-9aa0-08dc95ef5ab4",
        "createdDate": "2024-06-26T14:50:43.168235",
        "updatedDate": null,
        "createdBy": null,
        "updatedBy": null
    },
    {
        "totalPriceProduct": 539000,
        "shipFees": 30000,
        "finalPrice": 509000,
        "address": "Số 123, Phố Trần Hưng Đạo, Phường Trần Hưng Đạo, Quận Hoàn Kiếm, Hà Nội.",
        "phoneNumber": "string",
        "status": "CREATED",
        "user": {
            "firstName": "string",
            "lastName": "string",
            "address": "string",
            "id": "71aca016-8135-413d-949b-14b56de5d8af",
            "userName": "string",
            "normalizedUserName": null,
            "email": "string",
            "normalizedEmail": null,
            "emailConfirmed": false,
            "passwordHash": null,
            "securityStamp": "7b3086a6-5fbd-437b-aea5-2d499d853df9",
            "concurrencyStamp": "63045963-59bf-44c9-befa-dc86435fcf06",
            "phoneNumber": "string",
            "phoneNumberConfirmed": false,
            "twoFactorEnabled": false,
            "lockoutEnd": null,
            "lockoutEnabled": false,
            "accessFailedCount": 0
        },
        "id": "c709ae6f-1e55-452a-9aa0-08dc95ef5ab4",
        "createdDate": "2024-06-26T14:50:43.168235",
        "updatedDate": null,
        "createdBy": null,
        "updatedBy": null
    },
]

export const mockOrderDetails = {
    "id": "c709ae6f-1e55-452a-9aa0-08dc95ef5ab4",
    "totalPriceProduct": 539000,
    "shipFees": 30000,
    "finalPrice": 509000,
    "address": "string",
    "phoneNumber": "string",
    "status": "CREATED",
    "createdDate": "2024-06-26T14:50:43.168235",
    "orderDetails": [
        {
            "quantity": 300,
            "price": 539000,
            "productItem": null,
            "order": {
                "totalPriceProduct": 539000,
                "shipFees": 30000,
                "finalPrice": 509000,
                "address": "string",
                "phoneNumber": "string",
                "status": "CREATED",
                "user": {
                    "firstName": "string",
                    "lastName": "string",
                    "address": "string",
                    "id": "71aca016-8135-413d-949b-14b56de5d8af",
                    "userName": "string",
                    "normalizedUserName": null,
                    "email": "string",
                    "normalizedEmail": null,
                    "emailConfirmed": false,
                    "passwordHash": null,
                    "securityStamp": "7b3086a6-5fbd-437b-aea5-2d499d853df9",
                    "concurrencyStamp": "63045963-59bf-44c9-befa-dc86435fcf06",
                    "phoneNumber": "string",
                    "phoneNumberConfirmed": false,
                    "twoFactorEnabled": false,
                    "lockoutEnd": null,
                    "lockoutEnabled": false,
                    "accessFailedCount": 0
                },
                "id": "c709ae6f-1e55-452a-9aa0-08dc95ef5ab4",
                "createdDate": "2024-06-26T14:50:43.168235",
                "updatedDate": null,
                "createdBy": null,
                "updatedBy": null
            },
            "id": "fb272e4e-9111-4924-8de9-08dc95ef5ab1",
            "createdDate": "2024-06-26T14:50:43.1682342",
            "updatedDate": null,
            "createdBy": null,
            "updatedBy": null
        },
        {
            "quantity": 300,
            "price": 539000,
            "productItem": null,
            "order": {
                "totalPriceProduct": 539000,
                "shipFees": 30000,
                "finalPrice": 509000,
                "address": "string",
                "phoneNumber": "string",
                "status": "CREATED",
                "user": {
                    "firstName": "string",
                    "lastName": "string",
                    "address": "string",
                    "id": "71aca016-8135-413d-949b-14b56de5d8af",
                    "userName": "string",
                    "normalizedUserName": null,
                    "email": "string",
                    "normalizedEmail": null,
                    "emailConfirmed": false,
                    "passwordHash": null,
                    "securityStamp": "7b3086a6-5fbd-437b-aea5-2d499d853df9",
                    "concurrencyStamp": "63045963-59bf-44c9-befa-dc86435fcf06",
                    "phoneNumber": "string",
                    "phoneNumberConfirmed": false,
                    "twoFactorEnabled": false,
                    "lockoutEnd": null,
                    "lockoutEnabled": false,
                    "accessFailedCount": 0
                },
                "id": "c709ae6f-1e55-452a-9aa0-08dc95ef5ab4",
                "createdDate": "2024-06-26T14:50:43.168235",
                "updatedDate": null,
                "createdBy": null,
                "updatedBy": null
            },
            "id": "fb272e4e-9111-4924-8de9-08dc95ef5ab1",
            "createdDate": "2024-06-26T14:50:43.1682342",
            "updatedDate": null,
            "createdBy": null,
            "updatedBy": null
        },
        {
            "quantity": 300,
            "price": 539000,
            "productItem": null,
            "order": {
                "totalPriceProduct": 539000,
                "shipFees": 30000,
                "finalPrice": 509000,
                "address": "string",
                "phoneNumber": "string",
                "status": "CREATED",
                "user": {
                    "firstName": "string",
                    "lastName": "string",
                    "address": "string",
                    "id": "71aca016-8135-413d-949b-14b56de5d8af",
                    "userName": "string",
                    "normalizedUserName": null,
                    "email": "string",
                    "normalizedEmail": null,
                    "emailConfirmed": false,
                    "passwordHash": null,
                    "securityStamp": "7b3086a6-5fbd-437b-aea5-2d499d853df9",
                    "concurrencyStamp": "63045963-59bf-44c9-befa-dc86435fcf06",
                    "phoneNumber": "string",
                    "phoneNumberConfirmed": false,
                    "twoFactorEnabled": false,
                    "lockoutEnd": null,
                    "lockoutEnabled": false,
                    "accessFailedCount": 0
                },
                "id": "c709ae6f-1e55-452a-9aa0-08dc95ef5ab4",
                "createdDate": "2024-06-26T14:50:43.168235",
                "updatedDate": null,
                "createdBy": null,
                "updatedBy": null
            },
            "id": "fb272e4e-9111-4924-8de9-08dc95ef5ab1",
            "createdDate": "2024-06-26T14:50:43.1682342",
            "updatedDate": null,
            "createdBy": null,
            "updatedBy": null
        }
    ],
    "isSuccess": true,
    "errorMessage": ""
}